# Generated by Django 3.0.5 on 2020-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_auto_20200404_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='ok', max_length=50),
            preserve_default=False,
        ),
    ]
